name: "debezium_lab"
version: "1.0.0"
config-version: 2

profile: "debezium_lab"

model-paths: ["models"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +on_schema_change: "append_new_columns"
  enabled: "{{ (var('enabled', '') == true) | as_bool }}"
  debezium_lab:
    customers:
      alias: "{{ 'dd_' + var('customer') + '_customer' }}"
    people:
      alias: "{{ 'dd_' + var('customer') + '_people' }}"
